FORMAT: 1A
HOST: http://localhost:{port}/

# spring-cloud-demo

Polls is a simple API allowing consumers to view polls and vote in them.

## Accounts Collection [/accounts/]

### Create a New Account [POST]

创建新账户。

+ Request (application/json)

        {
            "nick_name": "gavin",
            "password":"123456",
            "mobile_phone":"13888888888"
            "email":"gavin.guo@mail.com"
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }