server:
  port: 8000

zuul:
  routes:
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
    account-service:
      path: /accounts/**
      service-id: account-service
    product-service:
      path: /products/**
      service-id: product-service
    order-service:
      path: /orders/**
      service-id: order-service
    payment-service:
      path: /payments/**
      service-id: payment-service
    delivery-service:
      path: /deliveries/**
      service-id: delivery-service
    point-service:
      path: /points/**
      service-id: point-service

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: http://localhost:9999/uaa/oauth/token
      user-authorization-uri: http://localhost:9999/uaa/oauth/authorize
    resource:
      user-info-uri: http://localhost:9999/uaa/user

logging:
  level:
    org.springframework.security: DEBUG

spring:
  aop:
    proxy-target-class: true
