version: '2'

networks:

  demo-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"

services:

  eureka-server:
    image: 192.168.1.88:5000/server-eureka
    networks:
      - demo-net
    ports:
      - 8761:8761
    restart: always

  config-server:
    image: 192.168.1.88:5000/server-config
    networks:
      - demo-net
    ports:
      - 8888:8888
    environment:
      - RABBITMQ_HOST=192.168.1.88
      - EUREKA_HOST=eureka-server
    depends_on:
      - eureka-server
    restart: always

  zuul-server:
    image: 192.168.1.88:5000/server-zuul
    networks:
      - demo-net
    ports:
      - 8000:8000
    environment:
      - EUREKA_HOST=eureka-server
    depends_on:
      - eureka-server
      - config-server
    restart: always

  oauth-server:
    image: 192.168.1.88:5000/server-oauth
    networks:
      - demo-net
    ports:
      - 9999:9999

  queue-server:
    image: 192.168.1.88:5000/server-queue
    networks:
      - demo-net
    ports:
      - 5680:5680
    environment:
      - RABBITMQ_HOST=192.168.1.88
      - EUREKA_HOST=eureka-server
    depends_on:
      - eureka-server
    restart: always

  zipkin-server:
    image: 192.168.1.88:5000/server-zipkin
    networks:
      - demo-net
    ports:
      - 9411:9411
    environment:
      - RABBITMQ_HOST=192.168.1.88
      - EUREKA_HOST=eureka-server
    depends_on:
      - eureka-server
    restart: always

  hystrix-server:
    image: 192.168.1.88:5000/server-hystrix
    networks:
      - demo-net
    ports:
      - 8989:8989
      - 8990:8990
    restart: always

  workflow-service:
    image: 192.168.1.88:5000/service-workflow
    networks:
      - demo-net
    ports:
      - 10100:10100
    environment:
      - MYSQL_HOST=192.168.1.88
    depends_on:
      - eureka-server
      - config-server
    restart: always

  account-service:
    image: 192.168.1.88:5000/service-account
    networks:
      - demo-net
    ports:
      - 10110:10110
    environment:
      - RABBITMQ_HOST=192.168.1.88
      - MYSQL_HOST=192.168.1.88
      - REDIS_HOST=192.168.1.88
      - LOGSTASH_HOST=192.168.1.88
      - EUREKA_HOST=eureka-server
    depends_on:
      - eureka-server
      - config-server
      - queue-server
    restart: always

  product-service:
    image: 192.168.1.88:5000/service-product
    networks:
      - demo-net
    ports:
      - 10120:10120
    environment:
      - RABBITMQ_HOST=192.168.1.88
      - MYSQL_HOST=192.168.1.88
      - REDIS_HOST=192.168.1.88
      - LOGSTASH_HOST=192.168.1.88
      - EUREKA_HOST=eureka-server
    depends_on:
      - eureka-server
      - config-server
      - queue-server
    restart: always

  order-service:
    image: 192.168.1.88:5000/service-order
    networks:
      - demo-net
    ports:
      - 10130:10130
    environment:
      - RABBITMQ_HOST=192.168.1.88
      - MYSQL_HOST=192.168.1.88
      - REDIS_HOST=192.168.1.88
      - LOGSTASH_HOST=192.168.1.88
      - EUREKA_HOST=eureka-server
    depends_on:
      - eureka-server
      - config-server
      - queue-server
    restart: always

  payment-service:
    image: 192.168.1.88:5000/service-payment
    networks:
      - demo-net
    ports:
      - 10140:10140
    environment:
      - RABBITMQ_HOST=192.168.1.88
      - MYSQL_HOST=192.168.1.88
      - REDIS_HOST=192.168.1.88
      - LOGSTASH_HOST=192.168.1.88
      - EUREKA_HOST=eureka-server
    depends_on:
      - eureka-server
      - config-server
      - queue-server
    restart: always

  delivery-service:
    image: 192.168.1.88:5000/service-delivery
    networks:
      - demo-net
    ports:
      - 10150:10150
    environment:
      - RABBITMQ_HOST=192.168.1.88
      - MYSQL_HOST=192.168.1.88
      - REDIS_HOST=192.168.1.88
      - LOGSTASH_HOST=192.168.1.88
      - EUREKA_HOST=eureka-server
    depends_on:
      - eureka-server
      - config-server
      - queue-server
    restart: always

  point-service:
    image: 192.168.1.88:5000/service-point
    networks:
      - demo-net
    ports:
      - 10160:10160
    environment:
      - RABBITMQ_HOST=192.168.1.88
      - MYSQL_HOST=192.168.1.88
      - REDIS_HOST=192.168.1.88
      - LOGSTASH_HOST=192.168.1.88
      - EUREKA_HOST=eureka-server
    depends_on:
      - eureka-server
      - config-server
      - queue-server
    restart: always

