server:
  port: 10110

spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/schema_account
    username: root
    password: root
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
  cache:
    type: redis
  sleuth:
    sampler:
      percentage: 1

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  config: classpath:logback.xml