server:
  port: 10110

spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/schema_account
    username: root
    password: root
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
  cache:
    type: redis
  sleuth:
    sampler:
      percentage: 1
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

security:
  oauth2:
    client:
      access-token-uri: http://localhost:9999/oauth/token
      user-authorization-uri: http://localhost:9999/oauth/authorize
      client-id: acme
      client-secret: acmesecret
    resource:
      #user-info-uri: http://localhost:9999/user
      token-info-uri: http://localhost:9999/oauth/check_token
      prefer-token-info: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.security: DEBUG