server:
  port: 10160

spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/schema_point
    username: root
    password: root
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
  cache:
    type: redis
  sleuth:
    sampler:
      percentage: 1

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

security:
  oauth2:
    resource:
      jwt:
        key-value:
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA95D+tHhkjB9lrW4KA5yn
          Lx68k0ouXWrlxkkRGzygk4eokMpZ2rZs0VzxQwhW5Pv+ag/uK9P4+8AjdW/WCld+
          xgDwizl/yIQb6BrRA27LsFjgO3x8jfZI8/M4k0MFkDrOxG8tDTTEJPwV9U+dU8qh
          r9QVqMPY/ZHogB9BrzDAMikFT9qqyNIy1f2CHTR6qXOFET62fh0Vzn25+w93tuZu
          1r/rJxW3lWPnfLW+sqRhqf6hyOwqBH7X8tPkWsxss4G3RcWqjBLOgCRRZnHi1koJ
          +Ai+sk2hdwmHNgcKcGYXCMzzjUgK7F54qvX1LpjG9wBbw72TDpo8wqNwRWif+Vw7
          5QIDAQAB
          -----END PUBLIC KEY-----

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.security: DEBUG

gavin:
  point:
    # 积分有效期限,单位:日
    period: 60

