server:
  port: 8888

spring:
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: classpath:/config
        git:
          uri: https://github.com/gavin-guo/config-repo
          username:
          password:

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest