server:
  port: 9999
  context-path: /uaa # 此处必须设定，否则无法获得token。

#security:
#  ignored: /css/**,/js/**,/favicon.ico,/webjars/**

spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/schema_auth
    username: root
    password: root
  thymeleaf:
    check-template-location: true

logging:
  level:
    org.springframework.security: DEBUG
