server:
  port: 10130

spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/schema_order
    username: root
    password: root
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
  cache:
    type: redis
  sleuth:
    sampler:
      percentage: 1

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

security:
  oauth2:
    client:
      access-token-uri: http://localhost:9999/uaa/oauth/token
      user-authorization-uri: http://localhost:9999/uaa/oauth/authorize
      client-id: acme
      client-secret: acmesecret
    resource:
      user-info-uri: http://localhost:9999/uaa/user

logging:
  config: classpath:logback-spring.xml


